api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "1099-dynamic-pricing"
type = "function"
uid = "39f11c64-5b9d-1993-3c2a-469d3c57c48b672767dc"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
